name: we_chat
description: A Chatting App Developed by Sameera
publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.13.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  firebase_messaging: ^15.1.6

  # Google sign-in and auth
  google_sign_in: ^6.2.2
  googleapis_auth: ^1.6.0

  # UI and utility packages
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  emoji_picker_flutter: ^3.1.0
  http: ^1.2.2
  flutter_notification_channel: ^3.1.0
  gallery_saver_plus: ^3.2.1
  lottie: ^3.2.0
  google_generative_ai: ^0.4.3
  intl: ^0.20.1
  lib: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottie/
