// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // iOS is explicitly unsupported based on your request.
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS. '
          'To add iOS support, run the FlutterFire CLI again and select iOS.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Sgyb5hexppcg24odYrzuwqBi-zVvWDo', // From your JSON: client[0].api_key[0].current_key
    appId: '1:401827602319:android:14bca6bcc7a9861cfc75fa', // From your JSON: client[0].client_info.mobilesdk_app_id
    messagingSenderId: '401827602319', // From your JSON: project_info.project_number
    projectId: 'wechat-189e7', // From your JSON: project_info.project_id
    storageBucket: 'wechat-189e7.appspot.com', // Derived from your JSON: project_info.storage_bucket
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc0O1gaLWlj2nK-Vvrk_Y0zwgh0RUW4fk', // From your JS config
    appId: '1:401827602319:web:60990df120e65fadfc75fa', // From your JS config
    messagingSenderId: '401827602319', // From your JS config
    projectId: 'wechat-189e7', // From your JS config
    authDomain: 'wechat-189e7.firebaseapp.com', // From your JS config
    storageBucket: 'wechat-189e7.appspot.com', // **Adjusted:** Typically projectId.appspot.com for Flutter
    measurementId: 'G-8XT0473K9Q', // From your JS config (optional, but good for Analytics)
  );
}